CREATE TABLE [Transactions].[Request]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [requestNumber] NVARCHAR(10) NOT NULL, 
	[totalQuantity] INT NULL,
    [PDD] DATETIME NULL, 
    [customerID] INT NULL, 
    [creationDate] DATETIME NULL, 
    [creationUserID] INT NULL, 
    [approvalDate] DATETIME NULL, 
    [approvalUserID] INT NULL,  
	[receiveDate] DATETIME NULL, 
	[receiveUserID] INT NULL,
	[rejectionDate] DATETIME NULL, 
    [rejectionUserID] INT NULL, 
	[rejectionReasonID] INT NULL, 
	[requestTypeID] INT NULL, 
    [requestStatusID] INT NULL, 
	[requestCalssID] INT NULL, 
    [requestPriorityID] INT NULL,

	CONSTRAINT [FK_CustomerID_Request] FOREIGN KEY ([customerID]) REFERENCES [Transactions].[Customer]([Id]),
	CONSTRAINT [FK_CreationUserID_Request] FOREIGN KEY ([creationUserID]) REFERENCES [Lookups].[User]([Id]),
	CONSTRAINT [FK_ApprovalUserID_Request] FOREIGN KEY ([approvalUserID]) REFERENCES [Lookups].[User]([Id]),
	CONSTRAINT [FK_ReceiveUserID_Request] FOREIGN KEY ([receiveUserID]) REFERENCES [Lookups].[User]([Id]),
	CONSTRAINT [FK_RejectionUserID_Request] FOREIGN KEY ([rejectionUserID]) REFERENCES  [Lookups].[User]([Id]),
	CONSTRAINT [FK_RejectionReasonID_Request] FOREIGN KEY ([rejectionReasonID]) REFERENCES [Lookups].[RejectReason]([Id]),
	CONSTRAINT [FK_RequestTypeID_Request] FOREIGN KEY ([requestTypeID]) REFERENCES [Lookups].[RequestType]([Id]),
	CONSTRAINT [FK_RequestStatusID_Request] FOREIGN KEY ([requestStatusID]) REFERENCES [Lookups].[RequestStatus]([Id]),
	CONSTRAINT [FK_RequestClassID_Request] FOREIGN KEY ([requestCalssID]) REFERENCES [Lookups].[RequestClass]([Id]),
	CONSTRAINT [FK_RequestPriorityID_Request] FOREIGN KEY ([requestPriorityID]) REFERENCES [Lookups].[RequestPriority]([Id]),
)
